### ISSUE TITLE
[1-17-6-7-4][Major] Soft crash when placing a decorative tile over crystal.

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#10]
![Adnotacja 2020-08-21 224019](https://user-images.githubusercontent.com/7067769/90951247-65d68000-e459-11ea-999f-34c579d5f243.png)

Thankfully, pressing Ignore allowed to continue working.

**Comment by whitelilydragon** [comment]
I managed to get the engine to give me a more specific error report, while performing exactly the same action repeatedly:

`
___________________________________________
############################################################################################
ERROR in
action number 1
of  Step Event0
for object obj_level_editor:

Tile does not exist.
 at gml_Object_obj_level_editor_StepNormalEvent_1 (line 2662) -                         var tile_scanner_ID = tile_get_background(o);
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Object_obj_level_editor_StepNormalEvent_1 (line 2662)`

I believe it's attempting to move a tile that no longer exists, so something is wrong with how I'm keeping track of tile IDs for the move tile code. I'll report back when I figured out how to fix it! Thank you for reporting; this is a highly-specific scenario that can't be isolated to just crystal flowers and decorative tiles.

**Comment by whitelilydragon** [comment]
I believe I have fixed this! Now, before attempting to move a tile that might not even be there, it checks if the tile exists first via the **tile_exists()** function. Before, I thought I'd only ever need to check whether the value was -1 or not, but that turned out to not be good enough in many cases.

I've been placing tiles over and around crystals, as well as picking them up over and around crystals, without spawning this error, but if it persists, or returns in a different way, please open a new ticket so we can address it.

Thank you for reporting!
