### ISSUE TITLE
[1.0.0.14][Normal] Carol wall cling + Spiked column can cause various problems. Can softlock

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#102]
Reproduction is somewhat honky and this issue can give random results.

Trying to cling to the Spiked Column as Carol, while trying to pounce or using Wild Kick can result in various bugs, shown below. Sometimes, you can get stuck in the position, efectively softlocking.

![Stuck](https://user-images.githubusercontent.com/7067769/107146461-bf1f6680-6948-11eb-8c68-648ac6cb3ff5.gif)
![Wut3](https://user-images.githubusercontent.com/7067769/107146462-c0e92a00-6948-11eb-8c5c-a21da3c7d697.gif)

**Comment by whitelilydragon** [comment]
I was able to fix this with a check for this particular animation in the swimming code, because thus far, this is the only character state affected by standing exactly at the same height as the water. (I still added some safety checks for everyone else, though! It's just a good idea.)

Thank you for reporting!
