### ISSUE TITLE
[1.0.0.16] Lilac's Uppercut goes too high

### ISSUE THREAD

**Issue by NitroSplint** [whitelilydragon/ShangMuArchitect#115]
In Freedom Planet, Lilac's Uppercut covers **102** vertical units.
I used the start of Fortune Night for the calculation. It's a flat surface, and an Uppercut there goes from y-position 522 to 420.

In Shang Mu Architect, it's **142** units.
For that, I used the block to the left at the start of `BouncyLauncher.map`. It's also a flat surface, and an Uppercut there goes from y-position 2080 to 1938 (rounded down).

**Comment by whitelilydragon** [comment]
This is interesting! I didn't realize Lilac's uppercut was so egregiously high, so after some fiddling with Lilac's code block, I not only fixed this to be almost accurate, just 0.48 pixels shy of the original's 102 pixels, (Which sometimes halves to 101.5, as well!) I got the uppercut glitch to perform more cleanly inside of Lilac's own code block- instead of depending on a nasty hack in the generic movement code block to make it work.

https://user-images.githubusercontent.com/23007238/108310713-d7ca2080-7181-11eb-95f4-17a7416fbcad.mov

Thank you for reporting!
