### ISSUE TITLE
[1.0.0.18][Lilac] Dragonboosting with a shield equipped gains immunity to Spikes

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#119]
If Lilac has any Elemental Shield (besides the Metal Shield which naturally provides Spike immunity) equipped and uses her Dragonboost, she can stand on spikes without her or the shield taking damage.

**Comment by whitelilydragon** [comment]
Turns out, this wasn't just an issue with Lilac, it was a general character bug!

Basically, if you have a shield, it freezes all code for the hurt state from executing. And inside that hurt code block, is a variable that fills back up to a value of 40, over 40 frames, after getting hurt. This is your invulnerability window between hits!

Lilac uses this to create 40 i-frames of invulnerability after performing her dragon boost, and it works really well! No side effects!

Or at least I thought, until y'all caught the shields freezing the i-frame counter inside the hurt code block, because again, shields freeze this entire block. Now, that i-frame counter is independent of *any* character state besides pausing the game, so it's working now! Lilac can get hit by spikes again

Thank you for reporting!
