### ISSUE TITLE
[1.0.0.18][Minor] Nonstandard screen resolution causes water UI elements to appear in front of black bars

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#120]
Black bars!!

getting back into issue finding!! this issue's a very minor one
https://user-images.githubusercontent.com/69790793/108448924-748acd80-7217-11eb-84c0-ffd2ac64b2bf.mp4

**Comment by whitelilydragon** [comment]
This was an easy fix! There are normally 64 pixel thick black bars drawn off-screen, because all HUD/GUI elements are drawn on the GUI layer, so whenever the window is stretched to a non-standard resolution, HUD elements that should've slid off-screen still appear above the game's internal resolution. The black bars help hide these sliding HUD/GUI elements

However, I had missed drawing a black bar to the left-hand side of the game window, because I didn't think I needed it- y'all proved me wrong.

Thank you for reporting!
