### ISSUE TITLE
[1.0.0.18][Minor] Pressing the same character button over and over again in the editor resets to standing; causes funny look

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#123]
https://user-images.githubusercontent.com/69790793/108453768-fe3e9900-721f-11eb-9ded-e5bb09850816.mp4

**Comment by whitelilydragon** [comment]
The only way I could fix this would be grasping every single context where it would be appropriate to change to certain states of animation, not just the character, and even then, it's important to keep those characters animation states and variables cleared out while swapping characters, otherwise horrible things happen. I'm sorry ; ^ ;
