### ISSUE TITLE
[1.0.0.18][Minor] Having enough downwards speed on downwards facing loop pieces causes characters to jet through them

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#127]
https://user-images.githubusercontent.com/69790793/108455580-5d51dd00-7223-11eb-9d9e-5f779d865a31.mp4

**Comment by whitelilydragon** [comment]
It appears that the slope tile in question was placed in a way that isn't cleanly connecting to the wall tile; it is 8 pixels off. You can enable debug mode to show the 2D logic controllers placed over slope tiles, it's what helps change the inside/outside collision maps for loop tiles. This can more plainly show how slope collisions are handled in this engine:

![image](https://user-images.githubusercontent.com/23007238/108457444-a6fcf080-7240-11eb-9638-e8407e52991c.png)

While this is a problem unique to Shang Mu Architect, even if I had used Damizean's collision model, (one of the most durable collision models!) it still could have ended with:

A) Lilac stopping abruptly, because a flat floor surface is perceived at the bottom
B) Running forward above the slope, missing it entirely (with an angle of 0)
C) Causing the player to twitch between the wall and slope and warp to the left of their position

Game engines don't like it when terrain tiles or objects have disparate alignments that are difficult for the sensors to resolve; it's tough to design a level maker game for this reason, because these scenarios that the internal stage designers would avoid, or be told to avoid by the programmers, are not a concern for players. Nor should it be; players don't have deadlines to worry about.

For that reason, I may adjust the 2D logic controller's boundaries to at least one pixel, to accommodate slopes being placed 8 pixels off, because if you're (literally) running into this issue- others will too. The game needs to show that something was misplaced, instead of flipping itself out this catastrophically, omg.

Thank you for reporting!

**Comment by benjistring** [comment]
Oh my gosh, I'd hardly realized that.
Thanks for the detailed response!

**Comment by whitelilydragon** [comment]
It's no biggie! ^ v ^ I'll close the ticket now.
