### ISSUE TITLE
[Anytime In The Future][Feature Suggestion] Difficulty tags on levels

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#128]
I've been playing a few of the prepackaged courses, and some of them are pretty hard! Some are also pretty easy.
Maybe this could be something to look into?

**Comment by whitelilydragon** [comment]
I think this is a genuine issue, because Freedom Planet in general is fairly harder than the average Sonic game. (Which is always the closest point of comparison.) This could help FP casuals immensely. I have added it to the community suggestions list!

Which can be found here: https://github.com/whitelilydragon/ShangMuArchitect#community-suggestions

Thank you for reporting!
