### ISSUE TITLE
[1.0.0.18][Major] Characters that collide with parts of a (non-floored) loop that aren't necessary for traversing it will glitch into or beside them.

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#137]
https://user-images.githubusercontent.com/69790793/108467714-82057f00-723a-11eb-9523-e06886e21c49.mp4

https://user-images.githubusercontent.com/69790793/108467723-8467d900-723a-11eb-9159-d91c9ba62982.mp4

**Comment by Deckardsmegson** [comment]
https://youtu.be/oglcm2IXElA

As demonstrated in this video, the loop tiles cause various zipping issues if you touch them from the outside (or inside), as well as the loop construct switching it's collision mask improperly, causing you to be able to walk on the tile preemtively instead of falling through it

**Comment by whitelilydragon** [comment]
I was able to fix this by adjusting the flat surface tiles placed around the exit loops to be thicker and longer around the weakspots along the loops!

https://user-images.githubusercontent.com/23007238/109106200-4e749a00-76fd-11eb-9909-c66d43bd5ddb.mov

Things broke when I decided it would be more efficient if the 2D logic controllers placed over certain loop pieces were removed by the loop exit controller- which meant that tile maps weren't getting swapped out for those loop pieces anymore; that's how the zips were happening.

I also adjusted the tile-switching boundary boxes of the top-left inside loop pieces to be more consistent with the top-right inside loop pieces, so that should reduce unintended zipping overall, as well!

Thank you for reporting!
