### ISSUE TITLE
[1.0.0.18][Minor][Accuracy issue] Objects that Milla finds in the ground appear behind her, and digging up multiple gems doesn't scatter them, so collection is very loud

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#142]

**Comment by whitelilydragon** [comment]
I originally had the object depths for items set behind the player, because otherwise they would draw over the HUD, but now that everything on the HUD is drawn on the GUI layer- there's no need for that, so I've fixed that, and changed the height at which gems drop, so Milla doesn't pick them all up at once!

Thank you for reporting!
