### ISSUE TITLE
[1-17-6-7-4][Minor] Setting new keyboard/joypad controls sometimes doesn't work after setting them once, playing a level, and going back to change them.

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#15]
![image](https://user-images.githubusercontent.com/69790793/90975872-e4303200-e4ec-11ea-9650-2cf7bb3e3c8a.png)
The escape key works fine, but mapping the keys has maybe a 50% chance of them all working again after setting them once, playing a level, and backing out.

**Comment by whitelilydragon** [comment]
I may need more exact steps to how the bug was surfaced, because I can't seem to reproduce it myself.

**Comment by whitelilydragon** [comment]
I've changed how saving key bindings works quite a bit, and haven't seen this crop up again, so I will assume this issue is either fixed, or persists via a different method that is unknown to me.

I think the reason this happened, is because before, button bindings were saved each time you entered a change, but those changes weren't always reflected _in memory_, from the title screen object, unless you specifically clicked on "Okay" with the A, C, or Start buttons; no considerations were made for canceling out of the controller bindings menu while some bindings had been modified.

Now, the title screen object's version of the controller's bindings are refreshed/referenced from the player object more frequently, and input bindings are only saved upon clicking "Okay", even if you've pressed the B button, so controlling the menus should still work after backing out of a level!

Thank you for reporting! If this issue persists, please create a new ticket!
