### ISSUE TITLE
[1.0.0.18][Minor] Ignited bombs are dormant when offscreen and only continue blowing up upon close player proximity

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#159]

**Comment by whitelilydragon** [comment]
As nice as this sounds on paper, it would be detrimental to the game's frame-rate on weaker computers, and may even complicate stage design. (Many classic video games relied on object activation ranges for certain tricks/stunts.) I will elaborate the justifications below, instead of coldly stating this as some nebulous "fact", like some people do! ; ^ ;

A) This is less a bug and more a consequence of how instance activation/deactivation works outside of the range of the camera. (Freedom Planet does this as well.) The game deactivates objects that are 196 pixels away from the camera's boundaries for performance's sake; weaker computers could not handle every object in a room asking for CPU time at once!

B) While there are certain enemies and object types I have made exempt from deactivation by the camera, I've only extended those exemptions to objects that needed stage-wide consistency- and don't scan for tiles.

Tile-scanning stacks up CPU time demands much quicker than every other tile function. The objects that are exempt from the deactivation range only manipulate tile IDs that they are given, and only scan for tiles upon their creation.

Bombs, however, do scan for tiles when activated, so if 20 bombs wanted to scan for tiles at all at once- 40% of computers running Shang Mu Architect may start to lag while they're active, and the slowdown won't stop until all of them have blown up, no matter how far away the player is from them.

C) Many stages, even in commercial games, tend to be designed around the fact that the player will only activate instances within certain ranges, so how the player experiences the stage is "timed" around this activation range. Having bombs blow up regardless of the camera's position could create situations that break specialized layouts with large rows of bombs, or kill wandering enemies ahead of the player in an untimely fashion.

For these reasons, I have to label this as #Won't Fix, I'm sorry ; ^ ;
