### ISSUE TITLE
[1-17-6-7-4][Minor/Improvement(?)] Sound for cracking shields and gem flowers much louder than the majority of the other SFX

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#16]
Probably the tiniest nitpick ever, but I believe it's a little loud compared to the original game-

**Comment by whitelilydragon** [comment]
That's because it was a legitimate mistake on my part! The petal shatter sound effect was not part of the scripts for adjusting the global volume of sound effects. (So if you lowered your in-game volume, the crystal shatter sound would be loud no matter what volume you chose!)

I have just fixed that, thank you for catching this! I completely missed this for _at least_ two years of the game's development.
