### ISSUE TITLE
[Release 1.0][Feature Suggestion] The side arrows in the editor's Enemies list still exist despite there being only one page

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#166]

**Comment by whitelilydragon** [comment]
More enemies are planned, as well as a sub-section for mod chips after release, so there will be more pages coming. It would take me half an hour to make it to where the arrows fade out if you're on the enemy sub menu, and I'd rather put that into more serious bugs- rather than having code that I will need to remove later, in the coming weeks after release.
