### ISSUE TITLE
[1.0.0.20] [Minor] Sound for destroying enemies that are knocked down when defeated do not play if screen is zoomed out

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#176]
https://user-images.githubusercontent.com/69790793/108594530-65973e80-732f-11eb-9fc4-eed83d445634.mp4

**Comment by whitelilydragon** [comment]
I have updated *all* enemies so that they can make sounds within a boundary box that scales with the player's resolution!

The only caveat is that in editor mode, all enemies are silent at non 1x zoom levels, because the noise levels would be too overwhelming with so many enemies within view. That much was intentional; what you reported, however, was an oversight on my part, *especially for player mode*, and I'm glad you caught it!
