### ISSUE TITLE
[1.0.0.22][Minor] Level music is now the quiet music this time around

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#187]

**Comment by whitelilydragon** [comment]
I made an oopsie in the level loading code! o ^ o The game was adjusting the audio gain of the song itself, instead of adjusting the gain for *all* songs based on a script that keeps all music consistently balanced, so it was going from quiet to extra quiet. I fixed this by using a silent version of the script I use for adjusting all music in the game!

Thank you for reporting!
