### ISSUE TITLE
[1.0.0.24] [MAJOR] Repeated loading results in graphical glitches and playing the same level forever

### ISSUE THREAD

**Issue by N00neIsHere** [whitelilydragon/ShangMuArchitect#191]
After repeatedly loading and exiting levels the following effects occur:
When loading into a level, the loading screen graphic remains on screen, preventing the player from seeing anything including the HUD and pause menu, although the level is loaded and can be played "normally". This graphical glitch can be fixed by dying or choosing restart.
Clearing the level or choosing exit from the pause menu will cause the transition wipe out to immediately play twice upon loading the level select, at which point the game will then load in the first stage in the list with the above graphical glitch.
This will happen on loop until the game is manually closed.

**Comment by whitelilydragon** [comment]
I was able to fix this by noticing a *very* silly oversight; some of the input variables used by the level select menu are *persistent*, so they're not automatically cleared each time you enter a new room; this can result in lingering held buttons on the menu, among other issues.

I've also implemented more input timer lock triggers for the player during these phases, and cleared their input variables, too, just to be the safe side! Thus far, I'm not seeing this happening anymore, but if it does occur again, feel free to post a new ticket, because the cause will be different even if the result is the same.

Thank you for reporting!
