### ISSUE TITLE
[1.0.0.24][Very unlikely] Beating a stage within the first 1-20 frames causes the game to freeze

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#196]
https://user-images.githubusercontent.com/69774625/109229972-6105d680-77c4-11eb-96fc-4c5cbc374f07.mp4

If you can destroy all targets within the first couple of frames of play, the game will freeze and need to be rebooted, since the player can not use any action-buttons while in the winning state. The only functional buttons are the keys F1-F12.

**Comment by whitelilydragon** [comment]
I have changed the tags, because this is a softlock, not a crash. Class A should only be reserved for catastrophic crashes that freeze the game and/or cause it to spit out errors and close itself

In any case, my solution to this was to limit how soon the brass targets specifically could be attacked; basically, for the first four seconds of a stage, its transparency is reduced to half, like a "ghost", and can't be interacted with at all! *Then*, it's allowed to be attacked again after those four seconds have passed.

This still means that it's possible to finish a stage in 3 seconds or less, but you also can't get a perfect 00:00:000 time attack record, or softlock the game, either.

Thank you for reporting!
