### ISSUE TITLE
[1.0.0.25] Moving Ground enemies zip loops upwards

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#202]
https://user-images.githubusercontent.com/69774625/109346038-5c4b2c00-7871-11eb-9d0b-61bebfb81cef.mp4

https://user-images.githubusercontent.com/69774625/109346083-6bca7500-7871-11eb-9655-cdf87c3fe83f.mp4

If an enemy that moves across the floor (Such as the Firespitter or Metal Pup) moves into a loop, it zips upward. This can cause various scenarios of them getting stuck or reaching the next floor.

**Comment by whitelilydragon** [comment]
I have made it so that the basic loop spawns in enemy direction tiles, but this is not really something I can rectify in the truest sense anytime soon. All moving enemies would need some comprehension of sloped wall surfaces like the player does, which will be awful for performance if many enemies are active at once.

There's also the fact that loops behave differently than they appear on the surface; flat surface tiles and sloped tiles in themselves can change their layer depth depending on the player's position, which sometimes brings us to the problem of the enemy getting the short end of the stick.

Perhaps if I'm able to refactor the collision system to rely on 2D masks instead of 1D masks, this could be an *easy* fix, but for now- it's a tricky thing to consider. Those enemy direction tiles exist in the meantime.
