### ISSUE TITLE
[1.0.0.27] Lilac's Training - A Ladder Too Short

### ISSUE THREAD

**Issue by Leo40Git** [whitelilydragon/ShangMuArchitect#212]
https://user-images.githubusercontent.com/7997354/109707947-72bff300-7ba3-11eb-8fbd-d5e56957196b.mp4

Ladder's *just* short enough that it allows you to jump off its highest point into the ceiling, methinks.
Also, Dragon Boost is *funky*.

**Comment by whitelilydragon** [comment]
Turns out, I had the collision code check too far up for ladders, (32 pixels above the floor!) which created more problems than just this, so I adjusted the value to 16, and all seems good!

https://user-images.githubusercontent.com/23007238/110196014-91c2bd00-7e0f-11eb-8787-27dba3eab3c2.mov

Thank you for catching this!
