### ISSUE TITLE
[1.0.0.27] Folders can be loaded as maps

### ISSUE THREAD

**Issue by Leo40Git** [whitelilydragon/ShangMuArchitect#213]
https://user-images.githubusercontent.com/7997354/109710316-34780300-7ba6-11eb-9e33-09be1f7f9c7c.mp4

According to this [cheat sheet](https://yal.cc/r/17/nsfs/), during a search, you need to check if the return value of `file_find_attributes_ns()` does *not* have the `fa_directory` bit set.
Also, you should check `nsfs_status` to make sure there aren't any errors. Trying to read a directory probably raises one.

**Comment by whitelilydragon** [comment]
I can't figure out how to implement this in a way that doesn't end the file search earlier than expected, but I have provided a warning to the player that their maps folder shouldn't contain other folders inside it:

![Screenshot 2021-3-5 23-18-5-0](https://user-images.githubusercontent.com/23007238/110194930-3988bc80-7e09-11eb-87d0-3e4e6530d060.png)

What this does is warn the player that the file search ended early because of the presence of the folder, so whichever file name the folder had will be wherever the file search ended. (So if your folder's name starts with an M, not even map files that start with M, N, or beyond, will have been found.) This at least stops people from loading blank maps.

Hopefully I'll be able to address this more cleanly after 1.0 is released. Thank you for reporting!
