### ISSUE TITLE
[1.0.0.44] - Restarting/playing one level after another doesn't reset the character's blue bar unless they are playing as Milla

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#226]

**Comment by whitelilydragon** [comment]
This was a thing that Freedom Planet 1 allowed too, as long as you had selected restart instead of entering a new level, but in SMA's case, there wouldn't be any real "performance" penalty on your time attack record by restarting from a previous checkpoint, so, I've made it reset not only upon restarting the room, or entering a new room, but it also resets each time you spawn the player while in editor mode!

Thank you for reporting!
