### ISSUE TITLE
[1.17.6.7.13] [Minor] Milla's (Super) Shield Burst hitboxes can still be changed midair and hit things

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#23]
https://cdn.discordapp.com/attachments/739994967186997329/748280898654437477/OWEI_MAI_MU_SHINDERU.mp4
https://cdn.discordapp.com/attachments/739994967186997329/748281296500818061/OWEI_MAI_MU_SHINDERU_2.mp4
https://cdn.discordapp.com/attachments/739994967186997329/748282519476240526/OWEI_MAI_MU_SHINDERU_3_and_controller.mp4

The animation is still buggy and it causes tiles as well as enemies to still be hit from the remaining particles.

**Comment by whitelilydragon** [comment]
Updated the case priority to minor. It is a hitbox size issue, (starts directly along the center of Milla's sprite) and the ending particle effect not correctly updating sometimes is known. It's not a critical logical issue, or a crash-producing bug.

This issue will be addressed and investigated, nonetheless. The remaining cosmetic bug and the hitbox's size are just too hard to miss even for a casual's eye

**Comment by whitelilydragon** [comment]
I've fixed the issue! It was a matter of the hitbox code needing to keep the hitbox locked to the direction that Milla's attacks were facing. Now, it checks if the skin is currently Milla, and uses Milla's version of xdir to scan either left or right for tiles to attack. Otherwise, the rectangular hitbox code behaves as normal.
