### ISSUE TITLE
[1.0.1.52][Collisions] Having a swing near a loop causes various clipping issues

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#234]
https://cdn.discordapp.com/attachments/739994967186997329/824059481172082698/2021-03-24_00-15-11.mp4

The video shows what happens if you place a swing that overlaps a loop. The end result is a crash if you run through at the "right" time.

**Comment by whitelilydragon** [comment]
I was able to solve this problem at least from the pendulum platform's and carasol's ends. They were correcting the player's relative X/Y positions too aggressively upon contacting with the player, and because all objects are always higher in the instance queue than the player object, they were basically allowed to overwrite the player's own X/Y coordinates/movement code, no matter what I did to address the issue from the player's end!

So, this has been partially fixed. It's still a bit janky if you try to run into sloped/curved ceilings while on moving platforms, but that seems to be a movement problem in general; I'll have to investigate this at that scope
