### ISSUE TITLE
[1.0.1.64] Walking into a diagonal wooden tile from below can get you stuck

### ISSUE THREAD

**Issue by ThatEps** [whitelilydragon/ShangMuArchitect#241]
From Flad's stream:

https://user-images.githubusercontent.com/38583427/118183238-8bba0f80-b442-11eb-9bc5-065ff98ad66f.mp4

**Comment by whitelilydragon** [comment]
Turns out, it was a piece code I specifically put in place as a safety measure, to keep people from wedging themselves inside of angled corners like this, while the collision system was in a much more fragile state.

Now that it's no longer necessary, I've instead set it to push people backwards if they're wedging themselves into a spot where an angled slope piece is going into the ground. (Regardless of whether or not it's flat!)

Thank you for reporting!

https://user-images.githubusercontent.com/23007238/177127863-3fadc613-2139-4919-8fe1-2a422d10a47f.mov
