### ISSUE TITLE
[1.0.1.64][Lilac] Dragonboosting into springs that are pushed into a ceiling can result in a crusher death

### ISSUE THREAD

**Issue by ThatEps** [whitelilydragon/ShangMuArchitect#243]
From Flad's stream:

https://user-images.githubusercontent.com/38583427/118186198-1cdeb580-b446-11eb-9f40-c18494cc1ee6.mp4

**Comment by whitelilydragon** [comment]
It gets much worse than that! Basically all characters suffer from this problem:

https://user-images.githubusercontent.com/23007238/122160823-9e0edb00-ce3e-11eb-8c7e-a9edd5ecd73a.mov

This will take some time to investigate

**Comment by whitelilydragon** [comment]
As of a recent attempt to fix this problem from Milla's end, the fix was generalized enough that even Lilac's dragon boost no longer has issues with ceiling springs! I've embedded springs into the ceiling and Lilac still doesn't warp into the ceiling, or get crushed by it!

Thank you for reporting! I apologize that this particular issue took so long for me to figure it out.
