### ISSUE TITLE
[1-0-1-93][Normal] Attacking a MegaCrate on slopes makes it temporary recent it's rotation.

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#249]
Prepare setup like this:
![image](https://user-images.githubusercontent.com/7067769/129250765-73287f45-a081-4119-80d8-2f177a8f1ba4.png)

Attacking the crate from the top will make it slide and for the moment, reset it's rotation to 0. Making it akward looking.

**Comment by whitelilydragon** [comment]
The cause of this was this object's misunderstanding of how to stay clipped on slopes, which I've not only fixed, but expanded on so that players could push against them even at non-zero angles!

https://user-images.githubusercontent.com/23007238/129650042-c9d0691d-0b51-4925-b1e9-527d8dfecb94.mov

Thank you for reporting!
