### ISSUE TITLE
[1.0.1.96] "This object can't use this item" Bullfrag enemy with keycard

### ISSUE THREAD

**Issue by 23LIEF** [whitelilydragon/ShangMuArchitect#256]
During a normal game, when the bullfrag enemy with the keycard takes effect, the screen "This object cannot use this item" appears and removes the bullfrag keycard, thus preventing the player from continuing on the map and the keycard is only returned back to the bullfrag after restarting the map with it appearing on the screen.

Here's a video explaining better if my English isn't helping much.

https://user-images.githubusercontent.com/89137194/129893974-f0d52754-d726-49d7-b80c-7a7d9b279bb6.mp4

**Comment by whitelilydragon** [comment]
This was fixed in a recently uploaded rolling release build! Apparently, the item giver object that spawns in, at the start of maps, wasn't checking the parent class for enemies, but instead the parent class for *all* objects placeable within the editor!

So, it was possible for it to attempt to give keycards/targets to nearby crystal gems or petal flowers, which would fail because those items can't use keycards/targets!

This confusion has been addressed, so now at worst, item givers might give keycards/targets to the wrong enemy; it shouldn't fail to outright give keycards/targets to enemies!

Thank you for reporting!
