### ISSUE TITLE
Error Importing .map.

### ISSUE THREAD

**Issue by GrapeSalesman** [whitelilydragon/ShangMuArchitect#257]
I tried to to import a .map from one computer to another computer to SMA. At first it worked properly, until I launched SMA using the launcher which then lead to this error message when I tried opening the map.

``
___
############################################################################################
FATAL ERROR in
action number 1
of Other Event: Room Start
for object obj_game_logic:

Push :: Execution Error - Variable Index [0,338] out of range [1,270] - -1.use_conversion_table(101181,338)
at gml_Object_obj_game_logic_Other_4
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Object_obj_game_logic_Other_4 (line -1)
``

I think it may be the version difference since the version of SMA the map was made on the first computer was the version from the download mirror (https://www.dropbox.com/s/127yi83wgal4pkv/Shang_Mu_Architect_1-0-0-44.zip?dl=0). I imported the .map to the August 18th 2021 build, which worked at first, but then when I launched the game with the launcher instead of the Shang_Mu_Architect_1-0-1-72 file, SMA could not open the file which lead to the message and me having to close out SMA entirely. I don't think it affected the file itself as I can still properly open it by just opening the game with Shang_Mu_Architect_1-0-1-72. Is there a way I could make the map not crash when opening with the launcher.

**Comment by whitelilydragon** [comment]
Older versions of the game didn't yet have any understanding of map version files, which newer versions of the game will have in their headers.

I'm only updating those values in the game for stable builds. (of which, a new one is coming soon!) It's tedious to remember to manually tweak the header's version number for every nightly to weekly build. Because of this, loading maps from one old rolling build to another will cause problems like this, as well.

That said, I'm not the one who developed the launcher, that would be our friend Leo! You may report the issue to his GitHub page for the SMA Launcher here:

https://github.com/SMALauncher/SMALauncher
