### ISSUE TITLE
Milla can clip through springs

### ISSUE THREAD

**Issue by TreyLina** [whitelilydragon/ShangMuArchitect#263]
Cool game
https://youtu.be/xs9j2oGous4

**Comment by whitelilydragon** [comment]
I was able to fix this by doing a number of things:

A) Gave Milla a spring check for fluttering, to prevent the fluttering from canceling out the spring state if it's activated mid-frame

B) Added a ceiling check for Milla's super shield burst, so it loses all of its speed if it touches a ceiling. I think the game was doing mostly fine without that extra check, but only indirectly! There were clearly edge cases where it'd still act up, so I've covered for this particular issue now

C) All downwards ceiling springs hard force the player's Y position to always start 48+ pixels below themselves, after hitting these springs. This doesn't look janky in motion, and prevents the exact ceiling collision issues you've posted here!

I don't fully understand why that course of action is necessary, because those ceiling springs don't have any flat collision tiles like the ground springs do, but they do! And it works, omg-

Thank you for reporting! This was a major issue
