### ISSUE TITLE
[1.0.7.4] [Minor] Text escapes the dialogue box's UI if a really long string is typed!

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#266]
![image](https://user-images.githubusercontent.com/69790793/163077880-484c431a-4bb6-47b0-9b30-8fa56d2d9448.png)

**Comment by whitelilydragon** [comment]
This is a known issue with Issue #254 as well. I'm going to leave this ticket open for now as I find a solution for it, but I felt it important to acknowledge that this is a longstanding GUI issue I've been stumped on.

I may have to resort to using surfaces to at least clip the drawing of text beyond certain boundaries, but having proper text-wrapping like you'd expect looks so much better. (And unfortunately, it's also the harder route.)

Hopefully I'll find a solution before 1.1's release > ^ <

**Comment by whitelilydragon** [comment]
I can confirm that this issue is fixed now! As well as we could hope it to be, at least

![Screenshot 2022-12-10 14-50-52-0](https://user-images.githubusercontent.com/23007238/206873048-dabefab2-3d4b-4301-af8e-38f140881749.png)

This is all thanks to our friend Leo! ( https://github.com/Leo40Git ) There are still edge-cases where it could do this, but they have been greatly reduced. Each time a character is typed, the NPC object is double-checking the length of the text and splitting it up as appropriately as it can

Thank you for reporting!
