### ISSUE TITLE
[1.0.7.4] [Minor] Multiple copies of the same actor can be placed in the same position

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#267]
![image](https://user-images.githubusercontent.com/69790793/163078398-c4e1b369-0163-4aaf-9527-49a2a09c7f88.png)

**Comment by whitelilydragon** [comment]
I feel silly, because in the process of setting up NPC saving in the editor, (which works so differently from saving normal objects/enemies) I forgot to place protections against this possibility!

There's now a warning if NPCs are placed within a 64px radius of each other:

![Screenshot 2022-4-14 13-24-52-0](https://user-images.githubusercontent.com/23007238/163441519-6eccab3b-6a9f-42e9-b3f4-4c938563d587.png)
