### ISSUE TITLE
[1.0.7.4] [Minor] The disco ball effect does not appear if the player is dancing a certain distance away

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#271]

**Comment by whitelilydragon** [comment]
This was a unique case! There seemed to be a 16 pixel gap where both the player's and disco ball's check circles couldn't intersect each other at the same time, and there's no easy way to fix that with the circles alone.

So, I added an additional scoped check that prevents the player from dancing if they are within range, but the disco ball's dance effects haven't been activated yet. (Because the ball itself hasn't yet seen the player.)

Thank you for reporting!
