### ISSUE TITLE
[1.0.7.4] [Minor] A player will never be able to escape from two sideways springs that are a wood block away from each other

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#272]
https://user-images.githubusercontent.com/69790793/163081221-370c2890-7c9c-4520-9fe9-5d7eac837b4d.mp4

**Comment by whitelilydragon** [comment]
Fixing this required two solutions, rather than one! I'll keep it simple:

A) The collision masks for the sideways springs used to be 4 pixels above the springs themselves, on purpose, long before boost pads were added to the game, so you could have springs acting as boosters. This, however, was neither accurate to the original game, or necessary to keep after we've added boost pads, so we can let go of this parameter. The collision box is now 1 pixel below the spring's sprite!

B) While the above fixes edge cases where the player can get stuck on top of springs, there's no way to address getting stuck from underneath springs without breaking the springs' usability in various stage layouts; adjusting their collision boxes to be shorter will even in some cases cause the player to push against the spring, before launching from it!

So, to prevent that scenario entirely, the editor now specifically looks at the sideways springs, and detects if their placement with springs of opposing directions are valid for working stages. This only applies to the sideways springs, because even awkward placement of all diagonal springs can't keep the player stuck- not easily, anyway

Recording of the illustrated solution:
https://user-images.githubusercontent.com/23007238/164055484-b9655047-6f04-44ff-9c8d-ebd7c8bf99ca.mov

Thank you for reporting!
