### ISSUE TITLE
[1.0.7.4] [Minor] Players can still resume in a hurt state if they're hurt right before the game is paused in the editor

### ISSUE THREAD

**Issue by benjistring** [whitelilydragon/ShangMuArchitect#274]

**Comment by whitelilydragon** [comment]
This is a longstanding issue with editor mode that was known, but I hadn't felt prompted to investigate until this bug report, and turns out, it was a *very* simple oversight! The hurt state itself wasn't getting cleared before spawning the player in, so it seems to have cleared up now. Thanks for reporting this!
