### ISSUE TITLE
Executable and meta.json version number differs from official release tag

### ISSUE THREAD

**Issue by hsandt** [whitelilydragon/ShangMuArchitect#275]
The release page https://github.com/whitelilydragon/ShangMuArchitect/releases indicates that latest version is 1.0.2.3 while inside the zip and in the provided meta.json, the executable is named "Shang_Mu_Architect_1-0-1-72.exe".

It's not a big deal, but as I am using https://github.com/SMALauncher to update the app, I had the impression that I didn't have the latest version (as 1.0.1 is before 1.0.2). In fact, they were the same. Probably not much to do now, but if you make another release, consider renaming the executable with a matching number.

**Comment by hsandt** [comment]
So I found out that the Discord server provided more recent weekly builds, which explains the issues tagged "1.0.7" around here.

However, they have the same issue, where 1.0.7.9 is in fact Shang_Mu_Architect_1-0-2-39.exe.

**Comment by whitelilydragon** [comment]
I'm labeling this as Won't Fix, because this is currently not a priority. It will be addressed for the final release builds and subsequent bugfix updates, but for the time being, having the executable being automatically labeled correctly would involve:

A) Game Maker Studio gives me no way to change this from the properties tab; all compiled game binaries go by the file name of the project itself. I would have to use "Save As" just to rename the project- which involves duplicating a directory with 10,000 files in it.

That takes a long while, if not cripples my hard drive's write queue while I still need to use my computer to do things!

B) Unzipping the compiled project, then renaming the EXE by hand, and zipping it back up. That is not something I can remember to do consistently!

C) The smarter thing to do would be not having the version number attached to the project's name itself, but that's not very practical while I'm still developing the game between my desktop computer and laptop. I would get source packages mixed up if I don't know what version number they correspond to when transferring them between both of my computers

For now, my main concern is reaching the finish line with this half-decade long dev cycle. I can't spare the energy for such a vanity as a version number on an EXE when I sometimes post a new rolling build every week.

**Comment by hsandt** [comment]
OK, I don't know much about GameMaker, but if you say so, I'm fine for having the correct number for the final version. I'm not sure how you transfer the project from desktop to laptop and vice-versa if Save As is so slow, but I guess you just do it less often (the big increase between 1-0-1-72 and 1-0-2-39 makes me think it was done at least 40 times, but maybe you skipped some numbers after all).

If for the final version you cannot do A) for some reason and go with B), you can write a script that unzips, renames, rezips (I did a similar thing with PICO-8, although it was simpler as it also exports binaries both in folders and zips). C) would also work for the final version, I guess, as you wouldn't have to switch computer anymore.
