### ISSUE TITLE
Carol gets stuck in the falling sprite and sounds go funny if you wildkick while ascending underwater from a spring

### ISSUE THREAD

**Issue by TreyLina** [whitelilydragon/ShangMuArchitect#277]
The wildkick sounds will sometimes get caught in a loop for a bit.

To trigger this bug, hit a floor spring underwater, wildkick while ascending, then hold it on long enough to the point where you start descending. Let go, and the titled results will happen. Very consistent.

You also can't use the regular claw attack in this state, but using the energy-depleting wildclaw works and resets you back to swimming normally.

**Comment by whitelilydragon** [comment]
It turns out this issue goes deeper than that! It doesn't matter if it's underwater or not, canceling the springing animation with wild claw attacks consistently breaks Carol's animation system until she lands on something.

So, I addressed this by having the attack code grab the current length of time from the spring timer, as well as your current speed and direction, then passes that onto the "flinging" system, so Carol's various state variables for her wildclaw attacks aren't interrupted by the spring animation ending.

Everything should be working normally now, with the tradeoff that canceling Carol's springing state with a wildclaw gives her extra height! And I'm just going to let her keep that, omg

https://user-images.githubusercontent.com/23007238/175920984-d7090fd4-4bb9-4bd2-aef9-47ad1a223d49.mov

Thank you for reporting!
