### ISSUE TITLE
Carol temporarily gets stuck in a walking state, unable to pounce in midair if you rolljump from a rising slope

### ISSUE THREAD

**Issue by TreyLina** [whitelilydragon/ShangMuArchitect#278]
To trigger this bug, you need to jump immediately after rolling up a slope. Try doing it nearby/on the slope rather than from a distance, as this increases the odds.

If you don't know how to trigger this bug, I can provide footage. I trigger it a lot and it's starting to drive me crazy...

**Comment by whitelilydragon** [comment]
This was a more specific issue I hadn't caught until now.

Basically, Carol's uncurling system was working too aggressively. If it detects that she needs to uncurl, (such as by rolling too slowly, or trying to turn around) it resets all of her rolling variables and forces her into the walking state, but it had no context for when you might want to uncurl while jumping.

So, that's why she was awkwardly flying upwards with her walking animation! This has been fixed now. She will uncurl into her jump animation, when jumping at low rolling speeds.

https://user-images.githubusercontent.com/23007238/175924226-24a19110-5bd3-425d-9c42-256fd985f49d.mov

Thank you for reporting!
