### ISSUE TITLE
Differences in momentum between FP and SMA

### ISSUE THREAD

**Issue by ChaosController** [whitelilydragon/ShangMuArchitect#281]
There is a slight difference in the momentum you gain or lose from slopes between SMA and FP. It may be hard to notice through video alone, as it's more of a "feel" thing, but here's a few comparisons between SMA and the original game.

https://user-images.githubusercontent.com/110129024/181653870-12497c57-85a0-4302-be29-b5841f6546b9.mp4

https://user-images.githubusercontent.com/110129024/181653890-6e318335-a4be-4709-8478-1bf39888fdb1.mp4

https://user-images.githubusercontent.com/110129024/181653916-1ffae6e5-3748-45a8-81e6-1e3e3dc21149.mp4

https://user-images.githubusercontent.com/110129024/181653932-ce0c00bc-c895-43ef-92f4-94ab2ebb0455.mp4

https://user-images.githubusercontent.com/110129024/181653955-e062fbfb-653b-4e21-abb5-c27018c9ba4f.mp4

https://user-images.githubusercontent.com/110129024/181653977-7e242c79-c0a3-446d-95ef-dd85f56b1d8d.mp4

https://user-images.githubusercontent.com/110129024/181654235-60bc86f3-99df-4638-b015-08c661a9b9fd.mp4

https://user-images.githubusercontent.com/110129024/181654268-e9d382ad-5fd5-43c7-82c4-53336cd213a1.mp4

The main difference I can gather from these is that in SMA you don't lose as much speed while walking up slopes, and gain more speed while walking down a slope. The rate at which you get momentum is also different. It's faster in SMA, but more gradual in FP.
As a side note, in the last clips when Lilac is launched off a ramp, she smoothly rotates into a vertical position in FP, while in SMA she roughly snaps into place.

**Comment by whitelilydragon** [comment]
Some of these differences are intentional, and others are issues that can't be reconciled with how differently Freedom Planet calculates slope factor, versus how Shang Mu Architect calculates that.

For instance, while I do have the correct physics parameters for all 3 of FP1's slope factor values, I don't have the trigonometric understanding I need to translate those values into slope factor formulas in SMA that translate as accurately as the original. (The way SMA's movement works is dramatically different from FP1.)

After half a year of tweaking it and teasing out the correct values from Freedom Planet with Flad's Freedom Trainer, I gave up and considered it close enough. Until I hit geometry and trigonometry math books at some point, I don't know how to "fix" this at all.

However, that last thing you noted about the fast rotation, I can look into that in the meantime! It absolutely shouldn't be doing that either way.
