### ISSUE TITLE
Various Spade animation bugs

### ISSUE THREAD

**Issue by TreyLina** [whitelilydragon/ShangMuArchitect#291]
Idle animation does not loop properly. It is most likely lacking the duplicate frames

The looking up animation jitters and is also lacking the duplicate frames for proper pacing.

The sighing animation looks like it's missing duplicates for proper pacing as well?

The head swish idle animation never plays.

Attack animation does not restart if you press it fast. So he just sorta freezes into place. Funnily enough, this only works while you're crouching.

**Comment by whitelilydragon** [comment]
I do have answers for each of these!

A) Idle animation indexes were incorrect; it was one frame off from looping like it should have, even prior to your new sprites

B) Looking up animation's start point was incorrect, which has been fixed

B) Sighing animation also had the wrong start point for its animation, which I have fixed, but I will not add the extra duplicate frames

This is why communication is key; I feel that I should have clarified the need for Spade's newer sprites to be as "drop in and replace" as possible. I would have to rewrite all of his existing animation data, and hard-wired attack code that checks for specific frame numbers, around the offsets that the additional frames would create

There is no time for this, or any of the unforeseen animation bugs these might create.

C) Shang Mu Architect only has one idle animation for each character, so it wasn't possible to add the additional animation where his head is turning

D) This, I may need footage for, because I can't seem to trigger it myself
