### ISSUE TITLE
Fatal error occur when starting gameplay

### ISSUE THREAD

**Issue by Lola-Noa** [whitelilydragon/ShangMuArchitect#301]
https://github.com/whitelilydragon/ShangMuArchitect/assets/159973539/3a205ccb-5cbe-494b-ade2-15904be5cefc

**Comment by whitelilydragon** [comment]
Apologies for the delay!

This is an issue that's long since been addressed. If you see this crash, please go to the Options menu and see the "Palette Shaders" menu item. Disable that, and the game will play normally.

Alternate palettes will be disabled as a result, but the gameplay experience will otherwise be unaffected. I hope you can enjoy the game. ; ^ ;
