### ISSUE TITLE
[1.17.6.7.21] [Minor] Milla's Phantomcube Trajectory

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#31]
Cubes have completely opposite behaviour from FP (They get thrown further in SMA on a standstill and shorter when running)

Behaviour in FP: https://cdn.discordapp.com/attachments/739994967186997329/752276785118576730/FP_Qyoobs.mp4

Behaviour in SMA: https://cdn.discordapp.com/attachments/739994967186997329/752276745293660200/SMA_Qyooobs.mp4

**Comment by whitelilydragon** [comment]
I've just fixed this! The issue had gone unnoticed, because there's a separate block of code for throwing cubes on non-zero angles, and angles 0 and 360. The block for zero degrees was set to throw cubes at a flat 5 pixels per frame, regardless of your own velocity, so I fixed that to apply to your horizontal speed as well, if you have any.

Thank you for reporting!
