### ISSUE TITLE
[1-17-6-7-23][Major] Walk on water in specific circumstances

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#33]
![image](https://user-images.githubusercontent.com/7067769/92813790-34026a80-f3c2-11ea-8abc-fb2b6557d06c.png)

In this situation, there are solids barely submerged under the water. Lilac can run on them easily, but you can also see, game considers her underwater. When she gets off the solids into the "pit" she doesn't lose here Y height and doesn't sink, making her effectively walking on water. She also sticks to running animation when hitting a wall, suggesting she is in a state of swimming.

**Comment by NBlastMax** [comment]
This could also work as a nice bug to show off in "bug reel" definitely looks amazing.

**Comment by whitelilydragon** [comment]
The problem was that the engine has never had any idea what to do when the Y position of the player *exactly* matched the Y position of the water's edge. It's- extremely horridly specific!

I fixed the problem by having it push the player 1 pixel into the water, if none of the ground sensors are active, (including the edge sensors) but your Y height exactly matches the water's height, and you're not falling. Thanks for reporting!
