### ISSUE TITLE
[1-17-6-7-23][Minor][Hard-to-reproduce] It seems that getting Water Shield while having Metal Shield sometimes makes you still immune to spikes

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#34]
Hard to reproduce sadly, but happened to me once. I will fill in more info if I manage to get it again.

**Comment by whitelilydragon** [comment]
This may be a general issue I've noticed with invincibility; sometimes the invincibility state doesn't go away, and I'm still not sure why.

**Comment by whitelilydragon** [comment]
I can't seem to replicate this issue, either, and I think it may have been related to this earlier bug you've reported:

https://github.com/whitelilydragon/ShangMuArchitect/issues/98

So, this issue may have been fixed, and even if it wasn't, the cause is likely different now; please open a new ticket if the issue persists.

Thank you for reporting!
