### ISSUE TITLE
[1-17-6-7-26][Major] Spikes kill you even when you have a half healthpetal remaining

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#42]
https://youtu.be/i8M9EhHIeFU?t=28
https://youtu.be/i8M9EhHIeFU?t=119

The above examples showcase an issue, where you die from touching Spike-like objects with half a petal remaining, which causes you to die.

**Comment by whitelilydragon** [comment]
I believe I have fixed the issue by increasing the negative range of the conditions for dying.

![image](https://user-images.githubusercontent.com/23007238/93414891-46701e80-f870-11ea-80f3-30a53dee0c7a.png)

The petal check is now -2.4, instead of -2.0, which leaves more wiggle room for damage by heavier hitting enemies/hazards. If this issue persists, please create a new ticket! Thank you for reporting!

**Comment by Deckardsmegson** [comment]
Issue has not been fixed. In fact, it's gotten worse. Everything that damages you and would kill you (if you have half a health petal, or a full health petal if hit by a bomb flower) will kill the player.
