### ISSUE TITLE
[1-17-6-7-27][Major] Spikes and enemies kill you even when you have a (half) healthpetal remaining

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#43]
Repoened because the change has not been fixed.

https://youtu.be/i8M9EhHIeFU?t=28
https://youtu.be/i8M9EhHIeFU?t=119

The above examples showcase an issue, where you die from touching Spike-like objects with half a petal remaining, which causes you to die.
Everything that damages you and would kill you (if you have half a health petal, or a full health petal if hit by a bomb flower) will kill the player.

**Comment by whitelilydragon** [comment]
I have refactored how "accident forgiveness" works, by reevaluating how the game handles these types of scenarios where the player is stunlocked by a barrage of attacks.

Turns out, instead of having reserve health beyond the health bar, the game just gives you an extra 20 frames of invincibility, 60 frames instead of the normal 40 frames, to escape the barrage before an enemy can kill you. It even interrupts checks for receiving further damage, until the i-frames are spent.

Thank you for reporting! We finally got the bottom of the issue this time, I hope.
