### ISSUE TITLE
[1-17-6-7-28+][Major] Shield Immunities

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#48]
Enemy attacks get nullified through the corresponding shield powerup in FP (Suggestions are in brackets):

Spikeball - Metal 
Spikewall - Metal
Metalpup - None (Should be Metal)
Blade Orbiter - None (Should be Metal)
Shock Puppet - Metal
Turretus - None (Fire or Earth)
Star Flounder -None (Water?)
Shark Torpedo - Earth
DNA-Cannon - None (Wood?)
Firespitter - Fire
BuoyBuoy - Water
Ghetto Blaster - Fire
Bullfrag - Water

**Comment by whitelilydragon** [comment]
I have implemented all of the shield immunities now! The only suggestions I didn't implement were:

Turretus - Its project doesn't correspond to any particular element, (like the shark torpedo's does, with its crystal bomb) so I wasn't sure which element would be appropriate for that

DNA Cannon - Similar problem, I'm not sure what element it could correspond to and it make sense for the player to discover experimentally

Otherwise, I just coded the rest in! Thank you for reporting and testing against all of these possibilities!
