### ISSUE TITLE
 [1-17-6-7-40][C] Moving enemies Ignore certain paths or zip into ceilings

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#53]
https://cdn.discordapp.com/attachments/739994967186997329/766727066124943401/2020-10-16_20-18-04.mp4

https://cdn.discordapp.com/attachments/739994967186997329/766727791965765672/2020-10-16_20-21-51.mp4

The above Videos show what happens when you grounded enemies touch a loop or slope and either overrides their original pathing or they zip upwards.

**Comment by whitelilydragon** [comment]
Both of these are difficult to resolve in different ways. For the first instance, it already takes a lot of decision-making on the metal pup's part to realize what it can and can't drive over, and when it should turn around on automatically on its own between two completely different surface types. I'm not sure how to expand its thought process on the matter beyond what it can already do.

As for the second instance- this is even more difficult, because unless the player has triggered the loop piece into turning into a scenery tile, while running through the loop, the metal pup will attempt to drive over the highest point of the bottom-left loop piece as it detects that loop. (So, whether or not it interacts with the loop correctly depends on which end of the loop the player has triggered) This clips it to the top of that tile, and then it later detects the outside version of the top-left loop piece tile, so it fully/completely zips up to the top of the loop.

Teaching it to turn around when touching the "wall" part the loop piece, without it getting stuck in a turning loop, has been challenging for me. The only recourse here is using enemy directional tiles to direct it away from certain obstacles, for now. This is something I may address for updates post 1.0.

Thank you for reporting!
