### ISSUE TITLE
[1-17-6-7-40][C] Throwable Cube during Supershield-Burst windup

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#54]
https://cdn.discordapp.com/attachments/739994967186997329/766716910981087243/2020-10-16_19-37-15.mp4

In the clip you can see that while charging the Supershield-Burst, you can throw an "invisible cube", which also resets your SBB into a regular shield burst.

**Comment by whitelilydragon** [comment]
This was also an easy fix! For now, I'm having the code for throwing cubes check against Milla's attack animations, because there's never a situation where she could physically throw her cubes while in those animation states; short-circuit evaluations should prevent those six extra conditional checks from being a micro-performance issue, but later on, I'll find a cleaner solution.

Thank you for reporting! I've never seen this happen during my own testing.
