### ISSUE TITLE
[1-17-6-7-40][C] Milla jumps immediately after Shield bursting (Burst Cancelling)

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#55]
https://cdn.discordapp.com/attachments/739994967186997329/766717100260720670/2020-10-16_19-37-28.mp4

If you hold your shield and press the jump button during this time, it will buffer a jump right after. The same happens with SSBs.

**Comment by whitelilydragon** [comment]
I was able to fix this by simply disabling the "jump_lock" variable in the animation system for Milla's ground-based attacks. This override prevents the variable from achieving a **true** condition, even when a **true** condition for allowing the player to jump is otherwise met.

Thank you for reporting!
