### ISSUE TITLE
[1_0_0_0][Normal] Characters can phase through loops on the right side.

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#57]
![image](https://user-images.githubusercontent.com/7067769/102260530-df1a4700-3f10-11eb-872e-83ef90af77fa.png)

It's very easy to phase through the right side of the loops, which might be problematic with the unique Loop exits.

1. Create a loop with exit facing downwards
2. Meet the loop on the other side like it's shown on the picture.
3. Pounce or bounce on the right side of the wall.

Sometimes you can phase-in the loop where you shouldn't.

**Comment by whitelilydragon** [comment]
Turns out, this was an oversight in how I coded the loop exit object; it was indiscriminately deleting *any* 2D tile-map switching nodes on the opposite side of the loop that it was placed on, which doesn't work (or make sense!) for loop exit configurations placed on the bottom of any loop piece.

Thank you for catching it, it's been fixed!
