### ISSUE TITLE
[1_0_0_0][Major] Shortly after hitting a spike or bouncePad, characters have a hard time landing on the FOF moving platforms

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#58]
1. Get to the spikes/moving platforms part of Bouncy Launcher
2. Fail the challenge

Expected: You should be able to land on the moving platforms.
Current: You cannot do that, Lilac needs to Cyclone to stabilize. Carol cannot stabilize with the Pounce.

**Comment by whitelilydragon** [comment]
I had a hard time rooting out this problem, but, turns out, I had the override timer for clipping to FOF surfaces too high. (This is to prevent problems such as the player's head going through ceilings on pendulum platforms.)

So, each time you bump your head on the ceiling, there'd be a 32 frame freeze on checking for collisions with FOF tiles again.

I've set the value to 16, and it's working in this particular area of bouncy launcher again!
