### ISSUE TITLE
[1_0_0_0][Minor] FoF platforms cannot contain enemies anymore. They drop.

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#60]
See picture. Turretus will fall down on the FoF Platform, when in old Bouncy Launcher versions, this worked.

![image](https://user-images.githubusercontent.com/7067769/102261945-b09d6b80-3f12-11eb-8b9b-f923166475ff.png)

Also, those FoF platforms aren't supposed to be being able to be turned into solids by Manual mode.

**Comment by whitelilydragon** [comment]
This is technically not a bug, because of how floating platforms and enemies have changed. Enemies now have their own gravity; even static enemies that do not move.

Enemies are attached to moving platforms by the controller node for the moving platform itself; enemies aren't directly scanning for floating platform tiles on the FOF Layer, so, without a controller node, they fall through.

There's another floating floor tile you could use instead, if necessary, but I could investigate allowing the FOF tiles to be placed manually on the slope layer, where enemies can in-fact read them
