### ISSUE TITLE
[1_0_0_0][Critical] Card Readers don't save/don't show up in levels

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#61]
Making a Card Door and saving the level, results in level without Card Reader present after entering it in play mode.

**Comment by whitelilydragon** [comment]
As it turns out, in some cases, the keycard terminal is spawned into the room before the doors are. (For instance, the player has to place the door first, before a keycard terminal will detect the door, instead of delete itself.)

This typically means that the keycard terminal is written to the map file before the door, so- yeah, I had to change when the terminal handles its door check and grabs the door's object ID, so it can manipulate the door as the user interacts with the terminal. Now, it performs this check 8 frames after spawning, which is more than enough breadth to find the door after it spawns.

Thank you for reporting!

https://user-images.githubusercontent.com/23007238/102945665-7ab93380-448c-11eb-8237-71933b0f551e.mov
