### ISSUE TITLE
[1.0.0.0] [Major] Placing multiple times at once does not work with a controller.

### ISSUE THREAD

**Issue by ElNachoCR** [whitelilydragon/ShangMuArchitect#62]
When placing multiple tiles at the same time it works correctly on a mouse, but when I attempt to do it on my controller it doesnt' work, I believe it's failing to pick up the button release when done on the controller.

https://cdn.discordapp.com/attachments/739994967186997329/788602932660273173/2020-12-15_21-04-38.mp4

As an added issue, since this stems from the same problem, doing it with the controller may leave ghost tiles and when attemtped to delete it crashes the game.

https://cdn.discordapp.com/attachments/739994967186997329/788603860650426368/2020-12-15_21-09-07.mp4

**Comment by whitelilydragon** [comment]
I was able to fix this, thanks to a long story that I'll make short!

Basically, any inputs made by controllers are ran through an input system that delivers inputs from either keyboards or joysticks, all through the same variables, so I don't have nightmarish AND or OR conditional spaghetti chains in my code. joy_input_jump gives the same numbers regardless of whether you're pressing a keyboard key or a controller button, simple enough.

But, the trouble comes in with the legacy mindset I had when first developing Shang Mu Architect. While Game Maker always offered keyboard press/release functions, it *never* did this for joysticks for classic releases, so I had to get creative with obtaining button presses/button holds/button releases.

Any inputs detected from a controller increments its relevant variable from 0 to as far as a floating point number can go, and when no further input is detected from that button, that value is reset to 0. Reading "1" from the variable meant that I could simply read a "press" event from the button, because it's always guaranteed to increment beyond that after the initial press. And if your player is a superhuman capable of only pressing for one frame, the value would still reset to 0 anyway. Simple enough.

But, it has one nasty downside: There are rare instances where I might need to tell if a button was just released, and I never could with this system. Simply using 0 to tell if a button was released is a recipe for disaster, as seen with this bug! 0 was assumed as the release in this case, so the algorithm for spawning tiles tied to button releases resulted in the loop either never starting, or never ending, because "no further input" suddenly means "just released" _forever_ in this context!

Fortunately, it turns out Game Maker Studio *does* have joystick press/release functions now, instead of only key press/release functions, so I was able to fix this problem without a bunch of headaches!

Thank you for reporting this, it was such an unexpected problem on my end!
