### ISSUE TITLE
[1.0.0.0] [Minor] Controller cursor camera panning becomes jank when moved to the right

### ISSUE THREAD

**Issue by ElNachoCR** [whitelilydragon/ShangMuArchitect#64]
This only happens with a controller, but if you pan the camera by pushing the cursor rather than using the right stick, when panning to the left it's smooth, but when panning to the right the pan stutters, the stutters increase if done on the top right corner.

https://cdn.discordapp.com/attachments/739994967186997329/788608113943117874/2020-12-15_21-25-47.mp4

**Comment by whitelilydragon** [comment]
For a minor issue, this has been a tough one to crack! Five hours later and I still can't make the panning movements as smooth as using the mouse. I can make the drawn cursor itself stutter less, but getting the panning movement itself to smooth out is proving more difficult than it should be.

Part of the difficulty is that Shang Mu Architect uses the GUI layer to both draw and handle GUI button interactions, which means the fan game also needs to grab the tic boxes for on-screen buttons relative to the mouse; on-screen positions that change as the user scales or full-screens the window, which Game Maker's GUI functions abstract away from you with **get** functions that scale from the game's internal resolution.

This is all super nice, but it makes simultaneous mouse support and joystick support a lot more tricky. The GUI layer works much simpler than you'd expect: Assuming a game's resolution is 426x240, you can draw a sprite at 64,96, and it will draw that precisely on the HUD without needing to draw it relative to the in-game camera. These assets also scale up if they are larger than you're drawing them, such as if the user scales up their window. This is how the thumbnail previews for tiles in SMA's tile menu look so crisp at higher resolutions.

That gorgeous simplicity can also be its curse, in this situation. The cursor still needs to interact with the "canvas", i.e, the room itself, with the mouse's coordinates in the room relative to the view's X/Y coordinates in the room, so that it can place objects/tiles onto the canvas with ease.

The cursor also needs to meaningfully interact with the GUI layer, too, so the drawing function for the cursor itself simply works with the direct mouse device coordinates, which draws the cursor relative to the view, window position, and game's internal resolution, the current zoom level, (i.e, the internal resolution increasing but still maintaining its original size, which allows the game to have a larger view without scaling up the window itself dynamically) as it scales up or down. Game Maker's functions then abstract all of this away very nicely with those window_device and window_get functions.

However, none of this allows the controller to manipulate the cursor as smoothly as before, because in order to streamline mouse/joystick-based inputs, I needed to use some math function silliness to make the analog stick directly control the mouse's movement on the canvas, for as long as the game has foreground focus, like so:


```C
if abs(edit_x) > joy_deadzone or abs(edit_y) > joy_deadzone
  {
      //Manipulate Real Mouse Position Based On Provided Coordinates
      var use_cursor_mouse_x = abs(use_cursor_x-view_xview[view_port]);
      var use_cursor_mouse_y = abs(use_cursor_y-view_yview[view_port]);
      var use_window_width  = window_get_width()  / view_wview[view_port];
      var use_window_height = window_get_height() / view_hview[view_port];
  
      window_mouse_set(use_cursor_mouse_x*use_window_width,use_cursor_mouse_y*use_window_height);
  }
```


This resolves the cursor's position on the GUI layer with the room-based coordinates of the mouse, whenever the joystick's analog stick is used, and it works great; the user would have no idea that the game's hijacking their actual mouse because of how nicely Game Maker handles everything, and doesn't keep control of it when the game loses focus. It even scales nicely with the zoom level and window width.

However, as you can see- there's no nice out-of-the-box way to handle panning based on the boundaries of the canvas. So, what I think I might need is, when the controller is active instead of the keyboard/mouse, a way to draw the mouse cursor on the GUI layer, based on the actual in-game coordinates of the mouse relative to the camera's position, so that joystick movement is smooth again. This is how its movement was smooth in builds prior to the completely thorough refactor of the GUI code, to work with the GUI layer.

Currently, I lack the algorithmic creativity to make that work, as I've explained, so I will have to leave this ticket for later; these are precious hours I could spend on equally pressing issues that aren't as puzzling to fix.

I'm leaving this ticket open until I have a solution, and when I do, I'll make a double post about how I fixed it, and close the ticket. Thank you for reporting!

**Comment by whitelilydragon** [comment]
Update: You want to know something dumb? All I had to do, all this time, was simply update the cursor's X/Y coordinates along with the panning speed of the camera boundaries, whenever the cursor's touching the edges of the screen.

The diagonal scrolling still a little needs work, I think I may need wider boundaries for the cursor touching the edges of the screen, but it's no longer scrolling like the game's running at 30 FPS each time you scroll up, right, or down, now!

https://user-images.githubusercontent.com/23007238/106439770-12278400-6446-11eb-8381-e8234b59477b.mov

Thank you for reporting!
