### ISSUE TITLE
[1.0.0.1] [C]  Carol's bike snaps to the floor too fast upon getting a gas can

### ISSUE THREAD

**Issue by ElNachoCR** [whitelilydragon/ShangMuArchitect#66]
This one's simple, the bike snaps to the floor almost instantly upon grabbing the can where in the official game it's in the air for about a second before hitting the ground again.

https://cdn.discordapp.com/attachments/739994967186997329/789680880904831007/Bike_Snaps_too_soon.mp4

**Comment by whitelilydragon** [comment]
I was able to fix this by forcing the double jump trigger variable (used for telling Carol's code that a gas can was touched, and thus, trigger the double jump code) to stay triggered for more than one frame. Just giving it an extra frame allowed it to work correctly!

Thank you for reporting this, because I had forgotten this was even an issue; it's a long-standing issue from the earliest days of development!
