### ISSUE TITLE
[1.0.0.1] [C] Touching a ceiling while jumping with the bike kills your momentum

### ISSUE THREAD

**Issue by ElNachoCR** [whitelilydragon/ShangMuArchitect#67]
So this is something I noticed in general testing, if you jump off a wall and you hit a ceiling it completely drops your speed on contact. Where as in the official game, ceilings (unless they're sloped weirdly and you snap to them because the game is dumb), don't affect your horizontal speed whatsoever, if anything it helps conserve it as ceilings completely negate airdrag.

https://cdn.discordapp.com/attachments/739994967186997329/789681420159287337/bonk.mp4

**Comment by whitelilydragon** [comment]
This was a little tricky, but fixing it was as simple as commenting out some *over-aggressive* speed-throttling of both axises whenever Carol's bike comes into contact with a ceiling! Now, it's only throttling vertical speeds whenever Carol's bumping against the ceiling, rather than also killing her horizontal speed.

Thank you for catching this!
