### ISSUE TITLE
[1.0.0.1][Minor] Controlstick Sensitivity and Screen Size resets after every bootup

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#68]
In the recording you can see that between rebooting the game (Be it manually or reloading with F2) the Controlstick Sensitivity and Screen Size settings reset back to their default value. 

https://cdn.discordapp.com/attachments/739994967186997329/791117593184174100/2020-12-23_02-33-35.mp4

**Comment by whitelilydragon** [comment]
As it turns out, I had never wrote any code to support saving the deadzone, as odd as that sounds! I had also neglected to let the variable that logs window scaling, to increment upon using left/right to scale the window. (It only logged which window scaled size you had set if you pressed the accept/jump button!)

The game also wasn't saving anything, if you had used the attack/cancel button to exit those menus, and return to the titlescreen. I did this because it sort of made sense at the time, but now, I think a lot of people just wouldn't know that the game's not saving anything if they double-tapped the attack/cancel button to exit the menu!

I've also made sure that the deadzone refreshes each time you change controller slots, if a controller is connected to that slot, of course!

Thank you for reporting, I had seriously missed these things! o ^ o'
