### ISSUE TITLE
[1.0.0.1][Minor] Walking into the ceiling from a loop tile causes you to clip inside them

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#70]
With the configuration seen in the video, you clip onto the end of the tile and if there is a ceiling, you will get crushed

https://cdn.discordapp.com/attachments/739994967186997329/791122460593487892/2020-12-23_02-50-57.mp4

**Comment by whitelilydragon** [comment]
I changed the bug class to C, because it's a collision issue, rather than a broader issue with the editor GUI, or softlocking.

Also, if you look closely, you can see the flat surface sensors popping up just as soon as you let go of a slope, which is what's zipping the player up through to the top of the tile- which then kills them if more tiles are obstructing their path above

https://user-images.githubusercontent.com/23007238/106986646-ce7c9500-6739-11eb-87bc-b60a97c2a1b8.mov

Right now, I'm looking into ways to mitigate this issue

**Comment by whitelilydragon** [comment]
I was able to resolve this, by putting a cooldown on when the flat surface floor and ceiling sensors could scan for tiles after declipping from a surface! It only lasts for one frame, but it's enough to let the flat surface wall sensors do their job correctly, before the floor and ceiling sensors attempt to clip onto the top of a flat surface tile.

https://user-images.githubusercontent.com/23007238/106994000-ee1bb980-6749-11eb-893d-4606c4eaf287.mov

This even made declipping from flat surfaces in general slightly smoother!

Thank you for reporting!
