### ISSUE TITLE
[1.0.0.2][Minor] Scene layer tiles obstruct the arms of pendulums and carousels, but not their platforms

### ISSUE THREAD

**Issue by ThatEps** [whitelilydragon/ShangMuArchitect#72]
Tried multiple scene layers. They all appear to obstruct the arms.

https://user-images.githubusercontent.com/38583427/103138367-8ef27000-46da-11eb-99b5-8097a8dfb429.mp4

https://user-images.githubusercontent.com/38583427/103138370-931e8d80-46da-11eb-98a1-015815ada6ff.mp4

**Comment by whitelilydragon** [comment]
I was able to fix this problem by just drawing all of the tiles instead, in the draw event, instead of manipulating tiles spawned into the room itself.

Given how much heavy-lifting these objects have to do as it is, it's silly not to take the extra steps to draw the bulk of the scenery tiles, instead of dealing with all the layering problems that come with tiles at layers higher than -5, or lower than 9. (Which means literally anything could draw over them!)

Only the platforms themselves are still tiles; the rest are all within the draw event now. The reason for this is that, if I were to spawn real tiles onto layers that wouldn't conflict with (most) tile scenery layers, they would still be readable by the cursor, which means even more exceptional tiles bloating the scripts/editor- and more unnecessary obstructions when placing tiles for players. And if I go higher in depth than that, to avoid the cursor scanning them, they'll start drawing over the player, too!

So, now both the pendulum platforms *and* carasol platforms should no longer pose such a layer problem! Thank you for reporting!
