### ISSUE TITLE
[1.0.0.2][Minor] In the editor, Lilac gets stuck in an infinite Dragon Boost if you boost along a set of boxes or bombs

### ISSUE THREAD

**Issue by ThatEps** [whitelilydragon/ShangMuArchitect#73]
Does not happen in play mode. Presumably because the boxes and bombs are indestructible in the editor.

https://user-images.githubusercontent.com/38583427/103138405-045e4080-46db-11eb-9ca5-9dba141e5dd7.mp4

**Comment by whitelilydragon** [comment]
This has been a long-standing issue that was never corrected, because I didn't know how to properly prevent infinite attack loops, even after refactoring the freeze frame system.

After some thinking, however, I came to the conclusion that triggering freeze frames for items you can't interact with in editor mode anyway, was superfluous, so I've just removed those extra lines of code to trigger the freeze frame system for non-destructible items, while in editor mode.

Thank you for reporting!
