### ISSUE TITLE
[1-0-0-6][Minor] Bomb SFX is strange.

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#79]
The moment Bomb is supposed to explode, you can here an additional beep, like it was attempting to start countdown again. Very minor thou.

**Comment by whitelilydragon** [comment]
I figured out that this was a simple sound call in the create event of the bomb object- which had no conditional checks over it. I've since removed that, and placed the initial beeping trigger sound into every code block where those bomb objects are first spawned into the room. It was a little tricky, but worth it!

Thank you for reporting!
