### ISSUE TITLE
[1-0-0-6][QoL] Indestructible items are obstructions to testing the level in Editor

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#80]
Like with the Keycard Gates, crates, bombs and other items, due to being indestructible in editor mode, can make testing the level in editor mode a bother and an annoyance.

Items in Editor Testing, IMO should behave as in normal Play mode, or there should be toggle to turn on/off the invicibility of the items, so user doesn't need to exit editor every time they want to test the level.

**Comment by whitelilydragon** [comment]
I can't make tiles behave exactly as they do in play mode, because they need to be respawned after play testing, and that creates memory pile-up over time.

However, it's an interesting discovery for me that instances don't seem to do this like they used to in legacy Game Maker runners, so while I'm not sure if I need to keep "memory pooling" in mind with objects or not, we're just going to roll with this and see how it affects memory performance over time: A modifier object that puts tiles on a different layer and lowers their transparency for two seconds, then returns them to normal, and deletes itself:

https://user-images.githubusercontent.com/23007238/103863906-a7299e00-508f-11eb-8263-1cd8c0f482f1.mov

Thank you for reporting! I was hesitant to even give this a try while left to my own thoughts on the matter.
