### ISSUE TITLE
[1-0-0-6][Performance] A lot of crystals can tank performance

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#82]
![Screen1](https://user-images.githubusercontent.com/7067769/103480052-47529f00-4dd2-11eb-9a3f-9209d01171df.png)

Consider this setup. When going through that obsticle, a lot of crystals can be generated which will tank performance significantly, unless crystals get collected. This needs to be discussed, if such slowdown is acceptable or not in that circumstance.

**Comment by whitelilydragon** [comment]
The crystal gem objects are about as well optimized as I can get them, so there's little I could do about that.

You'll notice that there's an instance counter for crystal gems while they're selected on the editor HUD; this flashes with a warning sign when an arbitrary limit is reached within the range of the camera. This is to help the player prevent slowdowns in their stages.

What I was able to do, however, was fix the slowdown in a different way; if there's less than 32 crystal gems within the range of the camera, the crates will spawn their five broken crate particle objects like normal. (Each have their own gravity and collision detection on two different tile layers.)

However, if there are more than 32 crystal gems within range of the camera, the crate particles stop spawning, and floating crystal gems are spawned instead of regular crystal games with collision detection. This seems to have fixed the slowdowns! Hundreds of floating crystal gems can be in the room on a complete potato computer like mine without any slowdowns.

Thank you for reporting!

https://user-images.githubusercontent.com/23007238/103750602-05de1180-4fd5-11eb-8c32-3df8dd313d46.mov
