### ISSUE TITLE
[1-0-0-6][Minor] Crystals from crates don't stop on crates when dropped.

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#83]
I believe crystals should stop on top of other crates when dropped from containers. It looks really weird when they phase through solid crates.

**Comment by whitelilydragon** [comment]
The crystals could originally land on other items, too, but this was removed because, currently, item collisions are on a separate layer from flat surface tiles, which means a third tile layer to check for collisions per frame by those items. It was a legitimate performance issue allowing each individual item to scan three tile layers simultaneously per frame.

However, when I can refactor item tiles to share the same tile layer as flat surface tiles, this will no longer be an issue, because they would be on layers that are already getting checked. Fewer layers, fewer performance problems!

I do appreciate that this was noticed, though. There's just nothing I can do about it while item collisions are currently handled the way they are.
