### ISSUE TITLE
[1-0-0-6][QoL] Level names should be possible to be longer.

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#84]
The level names are very limited in allowed characters. Gets a little annoying when for example you cannot name your level "Explosive Bunker" because of those limits.

**Comment by whitelilydragon** [comment]
The reason for this has a lot to do with the font for the level select menu. As you can see here, with your previous level project's name, it's taking up most of the space for stage titles on the description bar.

![Screenshot 2021-2-2 18-50-8-0](https://user-images.githubusercontent.com/23007238/106677923-af3e0600-6587-11eb-8f71-94db60173f45.png)

So, the reasons for the character limitation aren't technical so much as graphical. I'd need to produce an entirely new version of the font that is 12 pixels tall, instead of 17 pixels. And because the font doesn't accommodate European accent characters,  I would need to draw new characters for those, too. (The original font wasn't designed to be used for more than the title screen and level select menus, after all.)

For now, though, I'm keeping this on the to-do list, because surely there'd be time to make an extra custom font just for the stage titles after 1.0 is released! Then, I could expand on the level title's character limit without visually breaking the presentation. (And have actual character spacing!)

Thank you for reporting!
