### ISSUE TITLE
[1-0-0-6][Normal] Water can dissapear when removing Water Adjust item on the level.

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#85]
As it says on the tin. Water in a level simply disappears which is funny.
Water can re-appear when you place Water Adjust again.

**Comment by whitelilydragon** [comment]
I fixed this by having the water height adjuster return the water level to its default height (2,400px) upon getting destroyed. I was going to program the water height adjuster so that the water level could be deleted completely if desired, but it created problems in other areas anyway.

Thank you for reporting!
