### ISSUE TITLE
[1-0-0-6][QoL] Put Platform Switch Direction item in Items tab, not Tiles.

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#88]
This is kinda annoying how this important element is in completely different place than other Floating Platform elements.

Other elements could also have their placement re-positioned, like Enemy Movement Reverse.

**Comment by whitelilydragon** [comment]
Instead of doing that, your post prompted me to go out of my way to make placing moving platforms more intuitive than that:

https://user-images.githubusercontent.com/23007238/104433349-fff9aa80-5557-11eb-84a8-36041a175f28.mov

An upcoming build will allow you to choose which FOF tile you can place over these refactored controller nodes, but this is how moving platforms will be placed moving forward! Thank you for reporting!
