### ISSUE TITLE
[1-17-6-7-4][Major] Sound issues on enemies

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#9]
- Enemies are heard from quite afar.
- Enemies like Bullfrag seem to have their sound effects still audible after they are killed. This ends after few secs.

**Comment by whitelilydragon** [comment]
Enemies have recently been tweaked so that, if they are enemies with reoccurring sound effects, they're not allowed to play sounds if their X/Y coordinates are not directly within the camera's boundaries. (This scales with the zoom level, as well!) They're not even allowed to shake the camera if they're also not allowed to play sounds.

Allowing sound effects within the inactivation region outside the camera was too annoying. The only exception I made being the DNA Cannon, because it's critical to hear that thing thing coming!

I also added the bullfrag's sound effect to the audio scripts for the game, so now its sound effect won't be horrendously loud compared to the rest of the game, if you have customized your in-game volume.

Closing this ticket for now; if there are additional related issues with new builds, you're free to create a new post! Thank you for reporting the issue.
