### ISSUE TITLE
[1.0.0.9][Minor] Floating Platform 5 collision Issues

### ISSUE THREAD

**Issue by Deckardsmegson** [whitelilydragon/ShangMuArchitect#93]
The Floating Platform tile 5 is very broken, as the player stands on an invisible floor and you clip/zip onto the next platform, no matter the height difference. It also has no collision on the bottom or the sides at all.

https://cdn.discordapp.com/attachments/739994967186997329/799330695922581555/Sad_5.mp4

**Comment by whitelilydragon** [comment]
This has been fixed as of a recent update to the tile modifiers! Now, a flat surface tile is spawned in, (if the floating platform 5 tile is used) and its position manipulated alongside the floating platform tile. I also had to adjust the blank spaced padding on top of the tile, so that the FOF tile can be stood on correctly:

https://cdn.discordapp.com/attachments/739994967186997329/802791968513851402/2021-01-24_01-47-46.mov

Thank you for reporting!
