### ISSUE TITLE
[1.0.0.12][Normal] Tile not detected after entering level in Play, Edit modes or losing life.

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#97]
Working on the level, I noticed that at one point, game started to post error messages about "Tile Not Detected"

Happens with level provided below when:
- Booting up a level in Play Mode
- Booting up a level in Editor
- Losing a life and restarting from checkpoint.

[Elevator Shafts.zip](https://github.com/whitelilydragon/ShangMuArchitect/files/5897932/Elevator.Shafts.zip)

Looks like some tiles/object are left over when deleted. I have no idea which element could trigger this error message.

**Comment by whitelilydragon** [comment]
Do you know which object was providing the error message? "Tile Not Detected" alone tells me nothing. It could be either one of Game Maker's fatal error messages, or one the game prints out itself onto the editor HUD.

At the very least, I am aware that the player object can sometimes produce this error, so, I created a script that flushes out the values in all of the collision sensors, and even some physics parameters.

That should prevent instances where the player's code is frozen by editor mode's Edit button, then resumed later by either entering a new room in play mode, or resuming testing in editor mode, and any code that was previously running still expected previously scanned tiles to still be there. (And they won't be!)

I will need more details if you have them!

**Comment by NBlastMax** [comment]
I will look around. I think it might be related to new moving platforms components or DNA cannons since I noticed it being an issue at the end of my recent level creation. But I have no more clues as for now. I will keep you updated.

**Comment by whitelilydragon** [comment]
I've done hours of investigating this issue, and it's honestly hard to pin down, despite that I've narrowed it down to one very specific error message. (Despite making all error messages by node controller objects less vague.) It is not the result of overlapping tiles, nor is it any moving platforms getting sloppy with their tile management.

![Screenshot 2021-2-4 6-17-38-44](https://user-images.githubusercontent.com/23007238/106983460-f0731900-6733-11eb-979b-315b0cce413a.png)

This error means that the 2D Logic Controller was placed down over a space where there is not a loop-piece tile, or ramp tile. (This object controls which side of a loop-piece tile or ramp tile that you can collide with.) I'm not sure as to how that could happen, because these logic controllers delete themselves if they're sure that their tile no longer exists, so they should not have been present during the saving process.

Perhaps this will crop up in a different form later on, but it does not affect the functioning of your stage; it's only one rogue logic controller that deletes itself before I could reasonably have a chance to look at it. I can't yet find any exotic way to remove the logic controller without also deleting the tile.

In the meantime, I've disabled the error message from displaying during player mode; it will still be there during editor mode.

Thank you for reporting!

**Comment by NBlastMax** [comment]
Thank you very much for your investigation!
I will keep my eyes peeled. It's really strange, since I don't remember using Loop controllers at all in this level. I only used quarter loop tiles which I believe don't come with logic controllers.
Maybe I will pin it down in the future. I will keep you updated.

**Comment by whitelilydragon** [comment]
Loop tiles have a logic controller over them, as well, and it's their object that was generating the error. The loop controllers tend to delete most of the logic controllers and handle the inside/outside collisions themselves. (Reduces performance overhead and headaches from coordinating with other objects.)

If you figure out how to trigger this consistently, that would be a great help!
