### ISSUE TITLE
[1.0.0.12][Major] Carol can gain invincibility while Wild Kicking and interacting with springs.

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#98]
The proper way of reproducing this issue isn't clear, but it is similar to this. Elevator Shafts in Editor reproduces this issue.

Create a situation when jumping between bounce pads, you attack an enemy with a Wild Kick and land on the bounce pad, while attacking.

I noticed that I was immune to enemy damage and spikes after this. 

It looks like something major, but is difficult to reproduce.

[Elevator Shafts.zip](https://github.com/whitelilydragon/ShangMuArchitect/files/5897936/Elevator.Shafts.zip)

**Comment by whitelilydragon** [comment]
I investigated the issue itself, and the spring scripts are definitely interrupting the attack state variables for both Lilac and Carol. But because it's only clearing out their attack states, it could be leaving any use of invincibility turned on; I've made safety checks within the HUD's code *and* the spring scripts, to be sure that, if the invincibility timer is turned off, but the invincibility state itself is left on, it clears that out.

Because of this drastic change, I have no idea what all else it might affect, but this should have fixed this. If this problem persists in the next build, please open a new ticket with the specifics

Thank you for reporting! You may have finally found the illusive bug that allowed both Lilac and Carol remain invincible in unusual circumstances.
