### ISSUE TITLE
[1.0.0.12][Normal] Platform 5 is still extremely wonky with Carol's walljumps.

### ISSUE THREAD

**Issue by NBlastMax** [whitelilydragon/ShangMuArchitect#99]
Again. Elevator Shafts in the middle section shows the problem: 
[Elevator Shafts.zip](https://github.com/whitelilydragon/ShangMuArchitect/files/5897940/Elevator.Shafts.zip)

When you use Platform 5 in the horizonal movement mode, Carol has no problem jumping and clinging on it when the platform is moving towards her.

However, if the platform is moving away for her, she cannot cling to the platform properly and drops off imminently.

Also, it looks like collision box is uneven between the left and right side.

**Comment by whitelilydragon** [comment]
I have labeled this #wontfix, because:

A) It doesn't make sense mechanically, or physically.

I know Carol can drive up ladders on her bike, but you could sorta explain that with ladders potentially having a slight angle to them in the 3D aspect of space that we can't see from a 2D perspective; sliding down a surface that is moving away from you, not so much. Explaining things away as "video game logic" can only get you so far, before any suspense of belief is betrayed.

As well, the general consensus I've gotten from the GalaxyTrail community is that the current behavior makes more sense, and it might prove frustrating if Carol could essentially "magnetize" to surfaces moving away from her.

B) Implementing a way to allow this to work _will_ get too many wires crossed between the platform controller nodes and the player object, and especially in rare cases, any way I might program wouldn't work at all.

Each room in Game Maker has an "instance order" list, which defines which object gets to execute code first per frame. The highest object in the queue goes first, while anything else below them goes last. If the player object is somehow below the rest of the queue, any attempt at hooking the player object's X/Y coordinates either won't work, or won't work nicely because it wouldn't be pixel perfect.

It is important that any objects overriding the player's X/Y coordinates execute their code after the player's does, so any computed result is overwritten before the frame is fully drawn/rendered. Lagging behind a platform by a frame can both look ugly *and* result in Carol falling off of the platform instead.

While it is possible to manually define this order of execution, it must be done for each room where it would matter, (very tedious!) and given the nature of how this game loads map files, this order of execution can't be guaranteed. This is why I code against expectations of where objects might be on the room's instance order queue.
